Repository Ludy87/pyecotrend-ista, pull requests merged in 2024-06, with the labels that each got.

#161 🔨 Update files by <github-actions[bot]>
  ruff.toml
Labels: wait, in progress, bot

#165 🔨 Update files by <github-actions[bot]>
  requirements_test.txt
  src/pyecotrend_ista/login_helper.py
  tests/conftest.py
Labels: wait, in progress, bot

#166 replaces the variable name
  src/pyecotrend_ista/const.py
  src/pyecotrend_ista/pyecotrend_ista.py
Labels: bug

#171 🔨 Update files by <github-actions[bot]>
  src/pyecotrend_ista/pyecotrend_ista.py
Labels: wait, in progress, bot

#173 🔨 Update files by <github-actions[bot]>
  src/pyecotrend_ista/pyecotrend_ista.py
Labels: wait, in progress, bot

#192 Add get_account method for account retrieval
  src/pyecotrend_ista/pyecotrend_ista.py
  tests/__snapshots__/test_other.ambr
  tests/test_other.py
Labels: enhancement

#195 Fix typo in method naming
  src/pyecotrend_ista/pyecotrend_ista.py
  tests/test_consumptions.py
Labels: Bug: Fix!
